dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    update: true
    packages:
    - libboost-test-dev
    - libboost-log-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T ipfilter-prog-0.0.$TRAVIS_BUILD_NUMBER_amd64.deb -uvasilevnikitad:$BINTRAY_API_KEY "https://api.bintray.com/content/vasilevnikitad/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/ipfilter-prog_0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
